Loading rhel8/default-amp
  Loading requirement: dot rhel8/slurm singularity/current rhel8/global
    cuda/11.4 libpciaccess/0.16/gcc-9.4.0-6fonbj6
    libiconv/1.16/gcc-9.4.0-ahebbov libxml2/2.9.12/gcc-9.4.0-gnknt5e
    ncurses/6.2/gcc-9.4.0-aiirok7 hwloc/2.5.0/gcc-9.4.0-7sqomga
    libevent/2.1.12/gcc-9.4.0-hgny7cm numactl/2.0.14/gcc-9.4.0-52dwc6n
    cuda/11.4.0/gcc-9.4.0-3hnxhjt gdrcopy/2.2/gcc-9.4.0-e4igtfp
    knem/1.1.4/gcc-9.4.0-bpbxgva libnl/3.3.0/gcc-9.4.0-whwhrwb
    rdma-core/34.0/gcc-9.4.0-5eo5n2u ucx/1.11.1/gcc-9.4.0-lktqyl4
    openmpi/4.1.1/gcc-9.4.0-epagguv
Changed directory to /rds/user/tdb47/hpc-work/planning/thinker_private_planning/probing.

JobID: 58638934
======
Time: Sat Aug 10 09:20:27 BST 2024
Running on master node: gpu-q-29
Current directory: /rds/user/tdb47/hpc-work/planning/thinker_private_planning/probing

Nodes allocated:
================
gpu-q-29

numtasks=1, numnodes=1, mpi_tasks_per_node=1 (OMP_NUM_THREADS=1)

Executing command:
==================
python train_conv_probe.py --feature agent_onto_from --num_epochs 10 --weight_decay 0.001 --kernel 3 --model_name 250m 


test
=================================== FEATURE: agent_onto_from =========================================
Traceback (most recent call last):
  File "/rds/user/tdb47/hpc-work/planning/thinker_private_planning/probing/train_conv_probe.py", line 77, in <module>
    if type(trans[probe_args["feature"]]) == int:
KeyError: 'agent_onto_from'
